In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/Users/jacksonsorenson/Documents/Computational Media Lab/User Post Data and Code/post_data.csv')
df.head()

,username,title,selftext,created_utc,subreddit,score
0,test_user,Test Title,This is a test post,1234567890,test_subreddit,100
1,Fenveon11037,“My Dear Clematis” SGHR,Guess who got into Alien Stage back when Round...,1730795214,KieranDefenseSquad,14
2,Fenveon11037,So I made a Kieran papercraft,NaN,1724552135,KieranDefenseSquad,34
3,CursivePluto,The Happy Hob,The man did it \n\n[https://clips.twitch.tv/Co...,1553154956,darksouls,1334
4,CursivePluto,Console to PC,Plz I beg DE I want to play my game in the sup...,1518325846,Warframe,0

In [9]:
# Selfttext had null values, which was the users post, so drop na.
df = df.dropna(subset=['selftext'])

# The keywords set are related to vaping, e-cigarettes, smoking, and popular vaping brands.
keywords = ["vape", "vaping", "e-cigarette", "e-cig", "nicotine", "Juul", "smoke", "smoking", "pod", "elfbar", 
            "smok", "vaporesso", "voopoo", "lost mary", "geekvape", "uwell", "geek bar", "lost vape", 
            "eleaf", "elux", "flum", "bar juice", "elf bar"]

# This will show us if the post data has any of the key words while it iterates through the user's data.
def keyword(text):
    matched_keywords = [keyword for keyword in keywords if keyword in text]
    return matched_keywords if matched_keywords else None

# This is going to go through the "body" column, and pull the data where the keyword matches.
df['matched_keywords'] = df['selftext'].apply(keyword)
df_with_matches = df[df['matched_keywords'].notnull()]
df_with_matches = df_with_matches[['username', 'subreddit', 'selftext', 'matched_keywords']]

df_with_matches.head()

,username,subreddit,selftext,matched_keywords
52,Valenciana22,TheSinkingCity,"Hey y'all,\n\nSo I have a dilemma that I need ...",[elux]
266,floor_current,trees,I’m pretty young for a consistent user. I’m 21...,"[smoke, smoking, smok]"
268,floor_current,shrooms,"Hello, I’m posting to this subreddit because I...","[smoke, smok]"

In [10]:
# Turn into CSV
df_with_matches.to_csv('posts_keyword_matches.csv')